name: CI

# 트리거 설정: PR 생성, 동기화, 재오픈 시 실행
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

# GitHub Actions 실행에 필요한 권한 설정
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  # 첫 번째 Job: 코드 스타일 검사
  spotless:
    name: Code Style Check
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. JDK 21 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      # 3. gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Spotless로 코드 스타일 검사
      - name: Check code style with Spotless
        run: ./gradlew spotlessCheck

  # 두 번째 Job: 빌드 수행
  build:
    name: Build
    # spotless job이 성공해야 실행됨
    needs: spotless
    runs-on: ubuntu-22.04

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GIT_ACTION_TOKEN }}

      # 2. JDK 21 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      # 3. gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Gradle 빌드 수행 (테스트는 제외)
      - name: Build with Gradle
        run: ./gradlew build -x test